### ISSUE TITLE
Wowza SRT Url doesn't work

### ISSUE THREAD

**Issue by masaldana2** [WMSPanel/larix-sdk-examples#1]
I tried an srt url but it doesn't work, it only works with rtmp
I follow this tutorial and used the iOS-larix example
https://www.youtube.com/watch?v=3zw_IR2ck5s&t=6s

**Comment by WMSPanel** [comment]
You should consult Wowza Cloud support about that.

**Comment by masaldana2** [comment]
its the sdk, because it works on Larix app that's on the App Store  doing the grove url

**Comment by WMSPanel** [comment]
If you are a subscribed customer and you have problems with SDK please contact our support via help@wmspanel.com.
Thank you.

**Comment by masaldana2** [comment]
im a sub and this specific larix example doesn't work, that's why I opened a tix

**Comment by WMSPanel** [comment]
OK, now I got it. Please try the library from libmbl2_variants/rtmp_rtsp_srt/ directoru from SDK.
If you still have issues please post it to help@wmspanel.com .
Thank you.
