### ISSUE TITLE
lib missing in XCode.

### ISSUE THREAD

**Issue by ygmta** [WMSPanel/larix-sdk-examples#3]
![Screenshot 2021-08-18 at 18 27 20](https://user-images.githubusercontent.com/89141763/129902142-33bfec0c-aff6-4c61-bf0e-25a345a53740.png)

When i download code from git and try to run it, it's showing the libraries are missing and showing error.

**Comment by WMSPanel** [comment]
As we mention [in our Guide](https://github.com/WMSPanel/larix-sdk-examples/blob/main/ios-larix-demo/StepByStepGuide.md):

"Copy SDK headers and proper libmbl2.a library to project directory"

So you need to [subscribe to our SDK](https://softvelum.com/mobile/buy/), download the package and follow the guide.
